//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public string Password { get; set; }
        public string Login { get; set; }
        public string Passport { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public Nullable<int> Number_phone { get; set; }
    }
}
