//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Executor
    {
        public string FIO_E { get; set; }
        public string Expiriens { get; set; }
        public string Education { get; set; }
        public Nullable<int> Number_phone { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Passport { get; set; }
    }
}
